#!/bin/bash

xcompmgr &

# spawn trayer
trayer --edge top --align right --widthtype percent --width 11 --tint 0x353945 --height 21 --transparent true --alpha 0 &

# volumeicon
volumeicon &

# input method
fcitx &

# udiskie
udiskie -aN &

# nm-applet
nm-applet &

exec xmonad
